# Puerto por defecto
server.port=8080

# Configuracion de Gmail para el envio de correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dian.invoce@gmail.com
spring.mail.password=vaeu sofy qgwl togo

# Parametros de seguridad de JavaMail para Gmail (TLS y Autenticacion)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Logs de WS si es necesario para tu amigo
logging.level.org.springframework.ws=DEBUG
